config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'notifications/index'
  end
# deviseのルーティング
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :user, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'log_in', to: 'users/sessions#new'
    post 'log_in', to: 'users/sessions#create'
    delete 'sign_out', to: 'users/sessions#destroy'
    get 'sign_up', to: 'users/registrations#new'
    post 'sign_up', to: 'users/registrations#create'
    delete 'sign_out', to: 'users/sessions#destroy'
    # ゲストログイン機能
    post 'guest_sign_in', to: 'users/sessions#guest_sign_in'
  end


  # 管理者側のルーティング

  namespace :admin do

    resources :users, only: [:index, :show, :edit, :update]
    resources :overseas_areas, only: [:index, :edit, :update, :create, :destroy]

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# 会員側のルーティング
   scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'home' => 'spots#home'

  resources :spots do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update] do
    collection do
        get 'quit_check'
        patch 'quit'
    end
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end

    resources :messages, only: [:create,:destroy]
    resources :rooms, only: [:create,:show]

# 海外の雰囲気で検索
    get "area_search", to: "search#search", as: "search"
# お店の名前または住所で検索
    get "all_search", to: "spots#search", as: "all_search"
# 週間ランキング
    get "rank_search", to: "spots#rank", as: "rank_search"

# 通知機能
    resources :notifications, only: [:index]



  end

end

app/models/overseas_area.rb
class OverseasArea < ApplicationRecord

#   belongs_to :spot, optional: true
  # belongs_to :spot
  has_many :spots
  validates :name, presence: true

end

app/controllers/admin/overseas_areas_controller.rb
class Admin::OverseasAreasController < ApplicationController

  before_action :authenticate_admin!

  layout "admin"

  def index
    @overseas_area = OverseasArea.new
    @overseas_areas = OverseasArea.all
  end

  def edit
    @overseas_area = OverseasArea.find(params[:id])
  end

  def update
    overseas_area = OverseasArea.find(params[:id])
    overseas_area.update(overseas_area_params)
    redirect_to admin_overseas_areas_path
  end

  def create
    @overseas_area = OverseasArea.new(overseas_area_params)
    @overseas_area.save
    flash[:notice] ="ジャンルを追加しました"
    redirect_to admin_overseas_areas_path
  end

   def destroy
     @overseas_area = OverseasArea.find(params[:id])
     @overseas_area.destroy
     redirect_to admin_overseas_areas_path
   end


  private
  def overseas_area_params
    params.require(:overseas_area).permit(:name,:spot_id)
  end


end

app/helpers/admin/overseas_areas_helper.rb
module Admin::OverseasAreasHelper
end

app/views/admin/overseas_areas/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 mt-auto">
      <div class="row pb-3">
        <p class="col h3">Overseas area Edit</p>
      </div>
      <div class="row">
        <div class="col">
          <%= form_with model: @overseas_area, url: admin_overseas_area_path(@overseas_area.id),method: :patch, local: true do |f| %>
          <div class="form-group row align-items-center">
            <%= f.label :name,"name",class:"my-auto" %>
            <%= f.text_field :name, class: "ml-5" %>
            <%= f.submit "Update", class: "ml-5 btn btn-secondary" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/overseas_areas/index.html.erb
<div class="container">
    <div class="row">
        <h4 class="text-black px-4 mt-4">Overseas area List＆Addiction</h4>
    </div>
  　<%= form_with model: @overseas_area, url: admin_overseas_areas_path, local:true do |f| %>
    <div class="row">
      <div class="col-12">
        <table class="form-group table table-borderless col-6">
          <tr>
              <th>Overseas Area</th>
              <td><%= f.text_field :name %></td>
              <td><%= f.submit "Add", class: "btn btn-secondary" %></td>
          </tr>
        </table>
      </div>
    </div>
    <% end %>
    <div class="row">
        <div class="col-5">
            <table class="table ">
                <thead class="thead-light">
                    <tr>
                        <th>List</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <% @overseas_areas.each do |overseas_area| %>
                    <tr>
                        <td><%= overseas_area.name %></td>
                        <td><%= link_to " Edit", edit_admin_overseas_area_path(overseas_area), class:"btn btn-secondary" %></td>
                        <td><%= link_to "Delete", admin_overseas_area_path(overseas_area), method: :delete, data: {confirm: "本当に削除しますか？"}, class:'btn btn-outline-secondary' %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>