config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'notifications/index'
  end
# deviseのルーティング
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :user, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'log_in', to: 'users/sessions#new'
    post 'log_in', to: 'users/sessions#create'
    delete 'sign_out', to: 'users/sessions#destroy'
    get 'sign_up', to: 'users/registrations#new'
    post 'sign_up', to: 'users/registrations#create'
    delete 'sign_out', to: 'users/sessions#destroy'
    # ゲストログイン機能
    post 'guest_sign_in', to: 'users/sessions#guest_sign_in'
  end


  # 管理者側のルーティング

  namespace :admin do

    resources :users, only: [:index, :show, :edit, :update]
    resources :overseas_areas, only: [:index, :edit, :update, :create, :destroy]

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# 会員側のルーティング
   scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'home' => 'spots#home'

  resources :spots do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update] do
    collection do
        get 'quit_check'
        patch 'quit'
    end
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end

    resources :messages, only: [:create,:destroy]
    resources :rooms, only: [:create,:show]

# 海外の雰囲気で検索
    get "area_search", to: "search#search", as: "search"
# お店の名前または住所で検索
    get "all_search", to: "spots#search", as: "all_search"
# 週間ランキング
    get "rank_search", to: "spots#rank", as: "rank_search"

# 通知機能
    resources :notifications, only: [:index]



  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :spots, dependent: :destroy
   has_many :favorites, dependent: :destroy
   has_many :comments, dependent: :destroy
   attachment :profile_image, destroy: false

   validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
   validates :introduction, length: { maximum: 50 }

  # DM機能
   has_many :messages, dependent: :destroy
   has_many :entries, dependent: :destroy

  # フォロー機能
   has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
   has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
   has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
   has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  # 通知機能
  # 自分からの通知
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  # 相手からの通知
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy


   def follow(user_id)
    follower.create(followed_id: user_id)
   end

  # ユーザーのフォローを外す
   def unfollow(user_id)
     follower.find_by(followed_id: user_id).destroy
   end

   # フォローしていればtrueを返す
   def following?(user)
     following_user.include?(user)
   end

  # ログインしている時に退会済みのユーザーを弾く
   def active_for_authentication?
    super && (self.is_deleted == false)
   end

   # ゲストログイン機能
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guest"
      user.introduction = "こちらはゲストアカウントです。ユーザーの機能を利用することができます。"
      user.id = 99
    end
  end


   # フォロー通知
   def create_notification_follow!(current_user)
      temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
      if temp.blank?
        notification = current_user.active_notifications.new(
          visited_id: id,
          action: 'follow'
        )
        notification.save if notification.valid?
      end
   end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    before_action :authenticate_admin!
    layout "admin"

      def index
        @users = User.page(params[:page]).reverse_order
      end

      def show
        @user = User.find(params[:id])
      end

      def edit
        @user = User.find(params[:id])
      end

      def update
        @user = User.find(params[:id])
        @user.update(user_params)
        redirect_to admin_user_path(@user)
      end


    private

       def user_params
         	params.require(:user).permit(:name, :introduction, :profile_image, :email, :is_deleted)
       end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end



  # The path used after sign up.
  def after_sign_up_path_for(resource)
    user_path(@user)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController


  before_action :reject_user, only: [:create]

  # ゲストログイン機能
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user.id), notice: 'ゲストユーザーとしてログインしました。'
  end


  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end


  protected
  # ・if (@user.valid_password?(params[:user][:password])で、入力されたパスワードが正しいことを確認
  # ・(@user.active_for_authentication? == false))で、@userのactive_for_authentication?メソッドがfalseであるかどうかを確認
  # ・上記の2点が当てはまれば、ログインページにリダイレクトし、エラーメッセージを表示

  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if (@user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false))
        flash[:error] = "I have withdrawn.(退会済みです)"
        redirect_to new_user_session_path
      end
    else
      flash[:error] = "Please fill in the required fields.(必須項目を入力してください)"
    end
  end



# ここまで

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
 <div class="row">
    <div class="col-md-11">
      <h3 class="mt-2"><%= @user.name %>さん</h3>
    </div>
  </div>

  <%= form_with model: @user, url: admin_user_path(@user), local: true do |f| %>
  <div class="row">
    <div class="col-md-8">
      <table class="table table-borderless">
        <tr>
          <th>User ID</th>
          <td><%= @user.id %></td>
        </tr>
        <tr>
          <th style="width:60px"><%= f.label :name %></th>
          <td>
            <%= f.text_field :name %>
          </td>
        </tr>
        <tr>
          <th><%= f.label :email %></th>
          <td><%= f.text_field :email %></td>
        </tr>
      </div>
    </div>


    <div class="row">
      <div class="col-md-8">
        <!--form-inlineで横並びにする　flex-nowrapで折り返しなし-->
        <tr class="form-group form-inline flex-nowrap">
          <th class="form-group mr-3">status</th>
          <td class="form-group">
          　<%= f.radio_button :is_deleted, :false %>
          　<%= f.label :is_deleted, "有効", value: :false %>
          　<%= f.radio_button :is_deleted, :true %>
          　<%= f.label :is_active, "退会", value: :true %>
          </td>
        </tr>
        <tr>
          <td>
          <%= f.submit "Update", class: "btn btn-secondary" %>
          <% end %>
          </td>
        </tr>
    </table>
  </div>
</div>


</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="row">
        <div>
          <h2>User List</h2>
        </div>
      </div>

      <div class="row">
        <div class="col-10 mx-auto">
          <table class="table table-bordered">
            <thead class="thead-light">
              <th>
                <p>User ID</p>
              </th>
              <th>
                <p>Profile Photo</p>
              </th>
              <th>
                <p>User name</p>
              </th>
              <th>
                <p>email</p>
              </th>
              <th>
                <p>status</p>
              </th>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td>
                    <p>
                      <%= user.id %>
                    </p>
                  </td>
                  <td>
                    <p>
                      <%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %>
                   </p>
                  </td>
                  <td>
                    <p>
                      <%= link_to admin_user_path(user.id) do %>
                      <%= user.name %>
                      <% end %>
                    </p>
                  </td>
                  <td>
                    <p>
                      <%= user.email %>
                    </p>
                  </td>
                  <td>
                    <% if user.is_deleted == false %>
                     <p class="text-success">有効</p>
                    <% else %>
                     <p class="text-danger">退会</p>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <h3 class="mt-4"><%= @user.name %>さん</h3>
  <div class="row mt-4">
    <div class="col-5">
      <table class="table">
      <tr>
        <th>User ID</td>
        <td><%= @user.id %></td>
      </tr>
      <tr>
        <th>Profile Photo</td>
        <td><%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size:'80x80' ) %></td>
      </tr>
      <tr>
        <th>User name</th>
        <td><%= @user.name %></td>
      </tr>
      <tr>
        <th>email</th>
        <td><%= @user.email%></td>
      </tr>
      <tr>
        <th>status</th>
        <td><% if @user.is_deleted == false %>
        <p class="text-success">有効</p>
           <% else %>
         <p>退会</p>
          <% end %>
      </tr>
      </table>

    </div>

    <div class="col-8 mx-auto">
      <%= link_to "編集する", edit_admin_user_path, class:"btn btn-sm btn-info mx-3" %>
    </div>
  </div>
</div>