config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'notifications/index'
  end
# deviseのルーティング
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :user, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'log_in', to: 'users/sessions#new'
    post 'log_in', to: 'users/sessions#create'
    delete 'sign_out', to: 'users/sessions#destroy'
    get 'sign_up', to: 'users/registrations#new'
    post 'sign_up', to: 'users/registrations#create'
    delete 'sign_out', to: 'users/sessions#destroy'
    # ゲストログイン機能
    post 'guest_sign_in', to: 'users/sessions#guest_sign_in'
  end


  # 管理者側のルーティング

  namespace :admin do

    resources :users, only: [:index, :show, :edit, :update]
    resources :overseas_areas, only: [:index, :edit, :update, :create, :destroy]

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# 会員側のルーティング
   scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'home' => 'spots#home'

  resources :spots do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update] do
    collection do
        get 'quit_check'
        patch 'quit'
    end
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end

    resources :messages, only: [:create,:destroy]
    resources :rooms, only: [:create,:show]

# 海外の雰囲気で検索
    get "area_search", to: "search#search", as: "search"
# お店の名前または住所で検索
    get "all_search", to: "spots#search", as: "all_search"
# 週間ランキング
    get "rank_search", to: "spots#rank", as: "rank_search"

# 通知機能
    resources :notifications, only: [:index]



  end

end

app/views/layouts/_error_messages.html.erb
<% if obj.errors.include?(column) %>
  <ul class="error_explanation">
    <% obj.errors.full_messages_for(column).each do |message| %>
      <li class="text-danger small mt-1"><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0">

    <title>SmallOverseas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--ここからヘッダー-->
    <header class="mt-3">

    <div class="text-right mr-5">
      <% if admin_signed_in? %>
        <%= link_to "User", admin_users_path, class: "navbar-item btn btn-secondary" %>
        <%= link_to "Overseas Area",admin_overseas_areas_path, class: "navbar-item btn btn-secondary" %>
        <%= link_to "Sign out", destroy_admin_session_path, method: :delete, class: "navbar-item btn btn-secondary" %>
      <% end %>
    </div>
    </header>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <!--レスポンシブ対応-->
    <meta name="viewport" content="width=device-width,initial-scale=1.0">

    <title>SmallOverseas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!--slick導入のため下の2行を追加-->

    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
    <!--ここからヘッダー-->
    <header class="header">
  　<div class="navbar">
  　  <!--ロゴの表示-->
     <div class="navbar navbar-brand mt-3">
        <%= link_to root_path, class: "logo_link" do %>
          <div class="logo">
            <%= image_tag asset_path("logo.jpg", alt: "ロゴ") %>
          </div>
  　　　　 <% end %>
  　　</div>
  　　<!--ハンバーガーメニュー-->
    　<div class="navbar ml-auto">
      　<div id="sp-menu" class="text-center">
          <h2 class="mt-5 mb-5">MENU</h2>
            <% if user_signed_in? %>
              <p><%= link_to "ABOUT", about_path, class:"nav-menu-text m-2" %></p>
              <p><%= link_to "ALL SPOT", spots_path, class:"nav-menu-text m-2" %></p>
              <p><%= link_to "HOME", home_path, class:"nav-menu-text m-2" %></p>
              <p><%= link_to "MYPAGE", "/users/#{current_user.id}", class:"nav-menu-text m-2" %></p>
              <p><%= link_to "LOGOUT", sign_out_path, method: :delete, class:"nav-menu-text m-2" %></p>
            <% else %>
              <p><%= link_to "ABOUT", about_path, class:"nav-menu-text m-2" %></p>
              <p><%= link_to "ALL SPOT", spots_path, class:"nav-menu-text m-2" %></p>
              <p><%= link_to "LOGIN", log_in_path, class:"nav-menu-text m-2" %></p>
            <% end %>
        </div>

        <div id="hm-icon">
          <a class="menu-trigger" href="#">
            <span></span>
            <span></span>
            <span></span>
          </a>
        </div>

        <div class="box"></div>
        <div class="box"></div>
        <div class="box"></div>
        <div class="box"></div>
        <div class="box"></div>
        <div class="box"></div>
        <div class="box"></div>
        <div class="box"></div>

    </div>


    </header>

    <!--slickのための記述-->
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

    <%= yield %>

    <!--トップへ戻るボタン-->
　　<div id="pagetop"><a href="#"></a></div>

    <!--フッター-->

    <footer class="p-5 mt-5">
        <div class="myfooter">
          <div class="container">
            <div class="row">
              <div class="col-6 text-mated">
                <p class="contact">Contact</br><small class="text-muted">(お問い合わせ)</small></p>
                <p class="mail">Mail<i class="fas fa-envelope-square ml-1"></i>：<u><a href="mailto:info@small_overseas.com" id="info_mail">info@small_overseas.com</a></u></p>
              </div>
            </div>
          </div>
        <div>
            <div class="text-mated text-center copy_right">©small_overseas</div>
        </div>
      </div>
    </footer>



  </body>
</html>

app/views/layouts/top.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0">

    <title>SmallOverseas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!--下の2行を追加-->

    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
    <!--ここからヘッダー-->
    <header>
     <div class="navbar">
       <div class="navbar navbar-brand mt-2">
          <%= link_to root_path, class: "logo_link" do %>
            <div class="logo"><%= image_tag asset_path("logo.jpg", alt: "ロゴ") %>
            </div>
　　　　 <% end %>
　　　 </div>
　　</div>
    </header>
    <%= yield %>

     <!--フッター-->

    <footer class="p-5 mt-5">
        <div class="myfooter">
          <div class="container">
            <div class="row">
              <div class="col-6 text-mated">
                <p class="contact">Contact</br><small class="text-muted">(お問い合わせ)</small></p>
                <p class="mail">Mail<i class="fas fa-envelope-square ml-1"></i>：<u><a href="mailto:info@small_overseas.com" id="info_mail">info@small_overseas.com</a></u></p>
              </div>
            </div>
          </div>
        <div>
            <div class="text-mated text-center copy_right">©small_overseas</div>
        </div>
      </div>
    </footer>


  </body>
</html>